resolver: nightly-2019-10-06

packages:
- '.'

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps:
- FontyFruity-0.5.3.5@sha256:d0bbbc5bef14f229c8e90271365916b1b470bc0928ff4670f7d1885aec3378cf,2166
- Rasterific-0.7.4.4@sha256:05ca492a2c95e65da8d120281f5e579321cfe47b586a5730dce54ae1c52d1557,6008

# Override default flag values for local packages and extra-deps
flags:
  ffmpeg-light:
    BuildDemo: true
    BuildRasterDemo: true
    BuildVPlayDemo: true
    BuildTranscodeDemo: true

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
nix:
  enable: true
  packages: [ ffmpeg-full, pkgconfig, zlib, SDL2 ]
  pure: false

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

# nix-store -r $(nix-instantiate '<nixpkgs>' -A ffmpeg-full)
# extra-include-dirs: [/nix/store/nq5n4053yhkxwwlirjm4k8zh1r1hzc16-ffmpeg-full-3.0/include]
# extra-lib-dirs: [/nix/store/nq5n4053yhkxwwlirjm4k8zh1r1hzc16-ffmpeg-full-3.0/lib]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
