resolver: lts-15.6

packages:
- '.'

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps:
- Rasterific-0.6.1.1
- FontyFruity-0.5.3.2
- sdl2-2.1.3.1

# Override default flag values for local packages and extra-deps
flags:
  ffmpeg-light:
    BuildDemo: true
    BuildRasterDemo: true
    BuildVPlayDemo: true
    BuildTranscodeDemo: true
    BuildAudioExtractDemo: true
    BuildAudioSinDemo: true

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
nix:
  enable: false
  packages: [ ffmpeg-full, pkgconfig, zlib, SDL2 ]
  pure: false

# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

# nix-store -r $(nix-instantiate '<nixpkgs>' -A ffmpeg-full)
# extra-include-dirs: [/nix/store/nq5n4053yhkxwwlirjm4k8zh1r1hzc16-ffmpeg-full-3.0/include]
# extra-lib-dirs: [/nix/store/nq5n4053yhkxwwlirjm4k8zh1r1hzc16-ffmpeg-full-3.0/lib]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
